[tox]
envlist = reuse,changes,clean
skip_missing_interpreters = true
isolated_build = true
skipsdist = true
min_version = 4.3.3

[base]
deps =
    pip>=22.1
    build

[testenv]
skip_install = true
install_command = pip install {opts} {packages}
#basepython= python3.9

[testenv:{tools}]
envdir = {toxinidir}/.venv
# these tox env cmds share a virtual env using the following plugin in toxfile.py
# https://github.com/masenf/tox-ignore-env-name-mismatch
runner = ignore_env_name_mismatch

description =
    {tools}: Install pelican and dependencies into virtualenv

setenv =
    PIP_REQUIRE_VIRTUALENV = true
    PIP_DOWNLOAD_CACHE = $HOME/.pip/cache

passenv =
    CFLAGS
    CXXFLAGS
    LDFLAGS
    LD
    AR
    NM
    RANLIB
    PYTHON
    DISPLAY
    XAUTHORITY
    HOME
    USERNAME
    USER
    VERBOSE
    CI
    XDG_*
    GITHUB*

allowlist_externals =
    bash

deps =
    {[base]deps}
    ini2toml[full]
    -r requirements.txt

commands =
    {tools}: bash -c 'ls -lh ./*'

[testenv:reuse]
skip_install = true
passenv =
    PYTHON
    CI
    OS
    PYTHONIOENCODING
    PIP_DOWNLOAD_CACHE

deps =
    {[base]deps}
    reuse
    sbom4python
    distro2sbom

commands =
    reuse {posargs:"lint"}

[testenv:changes]
skip_install = true
always_copy = False

allowlist_externals =
    bash

deps =
    {[base]deps}
    gitchangelog @ https://github.com/sarnold/gitchangelog/releases/download/3.2.0/gitchangelog-3.2.0-py3-none-any.whl

commands =
    bash -c 'gitchangelog {posargs} > CHANGELOG.rst'

[testenv:clean]
skip_install = true
allowlist_externals =
    {[testenv:tools]allowlist_externals}

deps =
    pip>=21.1

commands =
    bash -c 'rm -rf output/ .venv/ __pycache__/'
